# Generated by Django 4.0.2 on 2022-02-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_bookmark_options_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='main_app.Genre'),
        ),
    ]
